### ISSUE TITLE
Crashes on "Launch App" for an app without a main/launcher activity

### ISSUE THREAD

**Issue by dkisselev** [ac-pm/Inspeckage#1]
Really amazing tool, truly awesome work!

I'm working with a widget-only app which doesn't have a defined main activity, Inspeckage should probably either check the manifest for a valid activity to start or try/catch the intent in case it crashes. It currently detects my configure widget activity which (I'm guessing) crashes because it expects to be launched from a widget intent and requires additional data.

**Comment by ac-pm** [comment]
Hi @dkisselev, I need a sample for testing. the widget is public? you can tell me the name?

**Comment by dkisselev** [comment]
Hey @ac-pm, unfortunately our app is currently private so I can't share that source, and I didn't get a chance to put together a simpler demo app, but it looks like DVDAndroid has worked out the problem in #3
