### ISSUE TITLE
"Module disabled" - cannot enable the Inspeckage module on Genymotion emulator

### ISSUE THREAD

**Issue by talkain** [ac-pm/Inspeckage#11]
Hey,

I was trying to install the module by following the "Genymotion + Xposed + Inspeckage" video.
I used the same image (5.1.0 api22) and the same packages that you published in your video (https://acpm.mobi/genymotion-xposed-inspeckage/).

For some reason after installing the Inspeckage module, the module cannot be enabled (The red labeled "Module disabled"). I did restart the emulator the same way you did and did checked the module in the Exposed's modules list with no luck.

Is there a way to troubleshoot this issue?

Thanks in advance!

P.S.
Amazing project. Well done :)

**Comment by talkain** [comment]
OK, so I managed to fix it. For the purpose of documenting this issue for future users, I saw a message in reddit:
https://www.reddit.com/r/xposed/comments/40jpch/help_modules_not_loading_mmb29p/

That suggest to get into the "App info" and clear the cache of the application.
I did that, also cleared the app's data and restarted the phone and it fixed the issue.

**Comment by youdy3000** [comment]
Hi @talkain thanks!  Your note helped me fix my problem.

**Comment by HumairaFasih** [comment]
Hi @talkain !!

This doesn't work with EdXposed on Android 11 on Genymotion Emulator.
