### ISSUE TITLE
Crash on error HTTP

### ISSUE THREAD

**Issue by Flo354** [ac-pm/Inspeckage#23]
Hi,

I have an application which crash on launch when inspeckage is enabled on it.
It seems to be an HTTP error, may be because they use squareup/okhttp ?

The crash log is attached below : 

> 05-09 20:39:34.644 28971 28971 I Xposed  : Inspeckage_Error com.android.okhttp.OkHttpClient#open(java.net.URI)#exact
05-09 20:39:34.644 28971 28971 I Xposed  : Inspeckage_Error java.lang.ClassNotFoundException: com.android.okhttp.internal.http.HttpURLConnectionImpl
05-09 20:39:34.684 28971 28971 E Xposed  : com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected value at line 1 column 14 path $.hookJson
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.Gson.fromJson(Gson.java:894)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.Gson.fromJson(Gson.java:844)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.Gson.fromJson(Gson.java:793)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.Gson.fromJson(Gson.java:765)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at mobi.acpm.inspeckage.hooks.UserHooks.initAllHooks(UserHooks.java:40)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at mobi.acpm.inspeckage.Module.handleLoadPackage(Module.java:126)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:203)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:729)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at android.app.ActivityThread.access$1800(ActivityThread.java:222)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at android.os.Looper.loop(Looper.java:158)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at android.app.ActivityThread.main(ActivityThread.java:7229)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:39:34.684 28971 28971 E Xposed  : Caused by: com.google.gson.stream.MalformedJsonException: Expected value at line 1 column 14 path $.hookJson
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:594)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
05-09 20:39:34.684 28971 28971 E Xposed  : 	at com.google.gson.Gson.fromJson(Gson.java:879)
05-09 20:39:34.684 28971 28971 E Xposed  : 	... 20 more
05-09 20:39:34.684 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /data/lp/xposed
05-09 20:39:34.684 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.694 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.704 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.714 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.724 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.734 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.744 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.754 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.754 28971 28971 I Xposed  : Inspeckage_FileSystem:R/W [new File(String)]: /storage/emulated/0
05-09 20:39:34.754 28971 28971 F art     : art/runtime/indirect_reference_table.cc:115]       505: 0x76b5f078 java.lang.String "Xposed"
05-09 20:39:37.144 25114 25114 I InjectionManager: dispatchPrepareOptionsMenu :de.robv.android.xposed.installer.XposedInstallerActivity
05-09 20:39:38.554 25114 25114 I InjectionManager: dispatchOptionsItemSelected :de.robv.android.xposed.installer.XposedInstallerActivity
05-09 20:39:56.304 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:39:57.254 25114 25114 I InjectionManager: dispatchPrepareOptionsMenu :de.robv.android.xposed.installer.XposedInstallerActivity
05-09 20:39:58.114 25114 25114 I InjectionManager: dispatchOptionsItemSelected :de.robv.android.xposed.installer.XposedInstallerActivity
05-09 20:39:59.024 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:10.484 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:12.844 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:17.084 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:19.414 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:23.694 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:26.044 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:50.404 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
05-09 20:40:52.694 29032 29032 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)

Thanks,

**Comment by ac-pm** [comment]
Hi @Flo354, the app that you are trying is public? I can test it?

**Comment by Flo354** [comment]
Thanks for your answer @ac-pm
The app is not public but I can give it to you in private if you want.

**Comment by ac-pm** [comment]
Yes, you can send to acpm.mobi[at]gmail.com

**Comment by Flo354** [comment]
Done

**Comment by ac-pm** [comment]
Please try the new version 2.0
