### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by smtking** [ac-pm/Inspeckage#24]
Hi Bro,

the app crash when I open it. 
I'm using Genymotion, the Android ROM version is 4.1.1(4.4.4 is the same).
below is the android LOG and the LOG shows in X
/ActivityManager(  286): Start proc mobi.acpm.inspeckage for activity mobi.acpm.inspeckage/.ui.MainActivity: pid=1321 uid=10055 gids={3003, 1015, 1028}

I/qtaguid (  286): Failed write_ctrl(s 1 10055) res=-1 errno=1

W/NetworkManagementSocketTagger(  286): setKernelCountSet(10055, 1) failed with errno -1

D/AndroidRuntime( 1321): Shutting down VM

W/dalvikvm( 1321): threadid=1: thread exiting with uncaught exception (group=0xa6317288)

E/AndroidRuntime( 1321): FATAL EXCEPTION: main

E/AndroidRuntime( 1321): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{mobi.acpm.inspeckage/mobi.acpm.inspeckage.ui.MainActivity}: java.lang.ClassNotFoundException: mobi.acpm.inspeckage.ui.MainActivity

E/AndroidRuntime( 1321): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1983)

E/AndroidRuntime( 1321): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)

E/AndroidRuntime( 1321): 	at android.app.ActivityThread.access$600(ActivityThread.java:130)

E/AndroidRuntime( 1321): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)

E/AndroidRuntime( 1321): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime( 1321): 	at android.os.Looper.loop(Looper.java:137)

E/AndroidRuntime( 1321): 	at android.app.ActivityThread.main(ActivityThread.java:4745)

E/AndroidRuntime( 1321): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 1321): 	at java.lang.reflect.Method.invoke(Method.java:511)

E/AndroidRuntime( 1321): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)

E/AndroidRuntime( 1321): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)

E/AndroidRuntime( 1321): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

E/AndroidRuntime( 1321): 	at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime( 1321): Caused by: java.lang.ClassNotFoundException: mobi.acpm.inspeckage.ui.MainActivity

E/AndroidRuntime( 1321): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)

E/AndroidRuntime( 1321): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)

E/AndroidRuntime( 1321): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)

E/AndroidRuntime( 1321): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1053)

E/AndroidRuntime( 1321): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1974)

E/AndroidRuntime( 1321): 	... 12 more

W/ActivityManager(  286):   Force finishing activity mobi.acpm.inspeckage/.ui.MainActivity

W/WindowManager(  286): Failure taking screenshot for (246x419) to layer 21010

W/ActivityManager(  286): Activity pause timeout for ActivityRecord{537fbd50 mobi.acpm.inspeckage/.ui.MainActivity}

I/qtaguid (  286): Failed write_ctrl(s 0 10055) res=-1 errno=1

W/NetworkManagementSocketTagger(  286): setKernelCountSet(10055, 0) failed with errno -1

I/Process ( 1321): Sending signal. PID: 1321 SIG: 9

I/ActivityManager(  286): Process mobi.acpm.inspeckage (pid 1321) has died.

2016-5-13 AM 11:56:16 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'vbox86p-userdebug 4.1.1 JRO03S eng.buildbot.20150610.092736 test-keys' with fingerprint 'generic/vbox86p/vbox86p:4.1.1/JRO03S/eng.buildbot.20150610.092736:userdebug/test-keys'
Loading modules from /data/app/mobi.acpm.inspeckage-1.apk
  Loading class mobi.acpm.inspeckage.Module
java.lang.ClassNotFoundException: mobi.acpm.inspeckage.Module
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:421)
	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by ac-pm** [comment]
Hi @smtking, please try android >= 5.1.x

Sorry, at the moment android 4.x is out of scope and I never try to use the Inspeckage in android 4.x. 

Please feel free to provide this improvement.

**Comment by smtking** [comment]
The APP was crash on launch, after I rebuild it, it can launch, I don't now why, but the Module still could not enable, after I googled, I found this https://github.com/rovo89/XposedBridge/issues/84
I figure out it is the xposedapi version requirement is too high so  I changed the build.gradle file in the dependencies section, then rebuild it, now the APP can run under ANDROID 4.x correctly, below is the change

provided 'de.robv.android.xposed:api:5+'

**Comment by ac-pm** [comment]
Thank you @smtking ! I will look that.
