### ISSUE TITLE
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by difcareer** [ac-pm/Inspeckage#25]
![image](https://cloud.githubusercontent.com/assets/5836680/15707698/b40b7728-282c-11e6-8920-04d15e34b4d2.png)

use google's Gson jar lead this error.   I suggest not use any third party jar.  if the hooked app use the same jar, this error accours.

**Comment by ac-pm** [comment]
Hi @difcareer, thank you for comment. The app that you are trying is public? I can test it?

**Comment by difcareer** [comment]
@ac-pm  it's my fault, I use a modifed xposed

**Comment by ac-pm** [comment]
ok @difcareer,  thanks for use it. If you have suggestions, please tell me.

**Comment by difcareer** [comment]
this is a wonderful module, I added some features, later I'll push them to you
