### ISSUE TITLE
Many apps crash at launch, some not.

### ISSUE THREAD

**Issue by incyclum** [ac-pm/Inspeckage#26]
Hi,

Many apps crash at launch like Snapchat or GIPHY.

In the Xposed logs I found the common error :

```
Inspeckage_Error com.android.okhttp.OkHttpClient#open(java.net.URI)#exact
Inspeckage_Error java.lang.ClassNotFoundException: com.android.okhttp.internal.http.HttpURLConnectionImpl
Inspeckage_FileSystem:R/W Dir: [...]
```

Using OnePlus X - Custom CM13.0 ROM - Xposed v85, Inspeckage 1.4.

Own build of Inspeckage beacause otherwise Xposed says it can't load module
beacause you have to disable Instant Run in Android Studio. So I rebuilt the APK
after disabling Instant Run in the IDE settings. No changes in graddle configuration.

Thanks for your help.

**Comment by ac-pm** [comment]
Hi @incyclum I will check the problem. Thankyou.

**Comment by incyclum** [comment]
I found only 3 usages of the class **com.android.okhttp.internal.http.HttpURLConnectionImpl**, in the file HttpHook.java:

```
(149-67) - final Class<?> httpURLConnectionImpl = findClass("com.android.okhttp.internal.http.HttpURLConnectionImpl", loadPackageParam.classLoader);
(151-40) - findAndHookMethod("com.android.okhttp.internal.http.HttpURLConnectionImpl", loadPackageParam.classLoader, "getOutputStream", RequestHook);
(152-40) - findAndHookMethod("com.android.okhttp.internal.http.HttpURLConnectionImpl", loadPackageParam.classLoader, "getInputStream", ResponseHook);
```

**Comment by incyclum** [comment]
- Apps are not crashing when the module is disabled.
- Removing any usage of the HttpHook class didn't stopped the apps to crash.

Continuing debugging...

**Comment by incyclum** [comment]
Placed some XposedBridge.log at some points of the code.
It tells me that all _Foo_Hook.initAllHooks in the Module class executed without anymore log
message.

Had a JNI ERROR message and Googled : http://forum.xda-developers.com/xposed/lollipop-module-crashes-art-jni-error-t3030586

Removed usage of FileSystemHook class and no crash.
