### ISSUE TITLE
Does 'New hooks' function support method parameters?

### ISSUE THREAD

**Issue by colordancer** [ac-pm/Inspeckage#28]
Let's say, I want to hook a method, void a(int a, String b). What should I write into the method box for the method's parameter? a(int, String)? a(int, java.lang.String)? or a[int, Ljava/lang/String;]?

BTW, 'New hooks' function is cool.

**Comment by colordancer** [comment]
I think I myself found the answer
`if(item.method != null && !item.method.equals("")) {
                for (Method method : hookClass.getDeclaredMethods()) {
                    if (method.getName().equals(item.method)) {
                        XposedBridge.hookMethod(method, methodHook);
                    }
                }
            }else {
                for (Method method : hookClass.getDeclaredMethods()) {
                    XposedBridge.hookMethod(method, methodHook);
                }
            }`

**Comment by ac-pm** [comment]
Yes @colordancer , you don't need specify parameters. Thank you for your feedback.
