### ISSUE TITLE
Module Disabled due to "Instant Run"

### ISSUE THREAD

**Issue by typoon** [ac-pm/Inspeckage#29]
Hello,

So I just installed the Inspeckage 1.3 module using Xposed Framework version 85. The module keeps reporting itself as disabled. By inspecting the Xposed error.log, I get the following:

```
04-15 04:48:55.444 I/Xposed  (  310): Platform: armeabi-v7a, 32-bit binary, system server: yes
04-15 04:48:55.444 I/Xposed  (  310): SELinux enabled: yes, enforcing: yes
07-06 11:01:26.133 I/Xposed  (  310): -----------------
07-06 11:01:26.136 I/Xposed  (  310): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
07-06 11:01:26.608 I/Xposed  (  310): Detected ART runtime
07-06 11:01:26.640 I/Xposed  (  310): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
07-06 11:01:26.952 I/Xposed  (  310): Loading modules from /data/app/mobi.acpm.inspeckage-1/base.apk
07-06 11:01:27.000 E/Xposed  (  310):   Cannot load module, please disable "Instant Run" in Android Studio.
```

Seems like the package being hosted has been compiled with the "Instant Run" option enabled. Xposed documentation mentions that this should be disabled:

https://github.com/rovo89/XposedBridge/wiki/Using-the-Xposed-Framework-API

> Please make sure to disable Instant Run (File -> Settings -> Build, Execution, Deployment -> Instant Run), otherwise your classes aren't included directly in the APK, but loaded via a stub application which Xposed can't handle.

Could you have a look into that?

Thanks!

**Comment by ac-pm** [comment]
Hi @typoon,

Please try the latest version 1.4 available here https://github.com/ac-pm/Inspeckage/blob/master/mobi.acpm.inspeckage_latest.apk

I will configure my android studio to prevent this.

Thanks a lot!

**Comment by typoon** [comment]
Just tried it, and still having the same issue. I uninstalled all modules and cleared the application cache before installing it (just to be safe), and still see the same error:

 ```
04-15 05:18:37.441 I/Xposed  (  292): Platform: armeabi-v7a, 32-bit binary, system server: yes
04-15 05:18:37.441 I/Xposed  (  292): SELinux enabled: yes, enforcing: yes
07-06 11:31:07.567 I/Xposed  (  292): -----------------
07-06 11:31:07.583 I/Xposed  (  292): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
07-06 11:31:08.061 I/Xposed  (  292): Detected ART runtime
07-06 11:31:08.093 I/Xposed  (  292): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
07-06 11:31:08.413 I/Xposed  (  292): Loading modules from /data/app/mobi.acpm.inspeckage-1/base.apk
07-06 11:31:08.460 E/Xposed  (  292):   Cannot load module, please disable "Instant Run" in Android Studio.
```

**Comment by ac-pm** [comment]
Interesting, because i don't use android studio 2.0. I opened the project one time, but I did the rollback. Maybe some parameter was changed. 

I will update my xposed framework to version 85 (84 at the moment) and try reproduce this error.

**Comment by ac-pm** [comment]
Ok @typoon, I updated my xposed framework and reproduce the error.
So with android studio 2.1.2 changed the instant run option and now is working. 

Please try with the updated apk.

https://github.com/ac-pm/Inspeckage/blob/master/mobi.acpm.inspeckage_latest.apk

**Comment by typoon** [comment]
Hey @ac-om, I just tried it and it works fine now!

Thanks for the help!
