### ISSUE TITLE
can U hook so?

### ISSUE THREAD

**Issue by c1erc1er** [ac-pm/Inspeckage#37]
What can hook SO or think?

**Comment by ac-pm** [comment]
Xposed is a framework for modules that can change the behavior of the system and apps without touching any APKs. What specifically do you want?

**Comment by rustymagnet3000** [comment]
Yes, @c1erc1er you can hook a dynamic library. But remember, some provider put run-time protections inside of the .SO file that can detect hooking.  So you need to workaround this by not starting inspeckage connecting to your app until the .SO file has been loaded.

**Comment by ohyeah521** [comment]
if u want to hook so ,i suggust u use cydia for android. it's very good for Android 4.0~4.4.4.

**Comment by max01203** [comment]
Hi, 
Inspeckage is a Xposed Module that can hook only the Java part, no control on the native side.
