### ISSUE TITLE
Individual app proxy?

### ISSUE THREAD

**Issue by msftsecurityteam** [ac-pm/Inspeckage#42]
I have spent the last hour messing around with the proxy'ing for an app but for the life of me I cannot get it to proxy traffic into my Burp proxy on my desktop. What am I missing? I enter in the proxy details on the local network, and the "Add proxy" button doesn't do anything, no indication of whether or not anything actually happened. Burp is running and sees no traffic. The HTTP hook however sees requests going out. What am I doing wrong?

**Comment by ac-pm** [comment]
The proxy through Inspeckage does not actually work on some applications that use Xamarin and Apache Cordova. In these cases you should try the proxy in the android wifi options.
