### ISSUE TITLE
Does possible pinning means ssl validation on the backend as well?

### ISSUE THREAD

**Issue by dimpol** [ac-pm/Inspeckage#44]
Hello great work on Inspeckage,

On the HTTP i see a "possible pinning" message what does that mean?
Maybe that the SSL validation is also performed from the backend as well (not only inside the mobile application)?

Thanks

**Comment by fpg1503** [comment]
Did you try using the SSL Unpinner?

**Comment by ac-pm** [comment]
Try the latest version. If doesn't work, please comment here.
