### ISSUE TITLE
Can i use Inspeckage to analyze data send from multiple devices on the same time

### ISSUE THREAD

**Issue by lasbel** [ac-pm/Inspeckage#46]
I want to ask if i can use Inspeckage to monitor what apps are sendind but from multiple devices on the same time. So i want to have a server with Xposed and Inspeckage and collect the data from devices that connect to that server,

Thanks in advance

**Comment by jodson** [comment]
I think that is not possible yet.

**Comment by lasbel** [comment]
Thank you for the reply

Στις 28 Ιαν 2017 7:01 π.μ., ο χρήστης "jodson" <notifications@github.com>
έγραψε:

**Comment by lasbel** [comment]
is it possible to connect to the GUI with 3g or 4g connection?

**Comment by ac-pm** [comment]
In this case you need use a USB cable and connect through ADB. 
"adb forward tcp:8008 tcp:8008"
And access in your browser:
"http://127.0.0.1:8008"

https://developer.android.com/studio/command-line/adb.html
