### ISSUE TITLE
cant see the parameters of get

### ISSUE THREAD

**Issue by ajmalkhanjamro** [ac-pm/Inspeckage#48]
first of of all thanks for making such awesome tool i have question i was inspecting an app call zipcar i used proxy and ssl unpinning to see  the api or parameters how it reests and headers stuff  but i was just able to see its url not the get parameters via it was requesting like username parameter or password parameter nothing in headers also is bug or i missed something btw i am using the fiddler as proxy to see headers please answer it clear because iam noob at this field

**Comment by ac-pm** [comment]
You can try add new hooks in "+ Hooks" tab. But I really recommend you use a "proxy tool", like Burp Suite.

**Comment by ajmalkhanjamro** [comment]
i used the proxy tools buddy but still now able to see thats buggin me out its showed me their url where they were reuesting but not parmeters
