### ISSUE TITLE
SERVER INTERNAL ERROR: Serve() returned a null response.

### ISSUE THREAD

**Issue by clviper** [ac-pm/Inspeckage#5]
Hi there.

I am getting this error if I try to download a file using the Tree view or try to take a screenshot of the app.

Awesome project. Keep it up.

**Comment by ac-pm** [comment]
I've seen these errors when I deny the root permission for screenshot and when the files to download are big. These error and others are in my to-do list! Thank you for collaborating.

**Comment by clviper** [comment]
Thank you. No problem. Glad to help.

**Comment by ac-pm** [comment]
Please try v2.0
