### ISSUE TITLE
Crash when opening Config

### ISSUE THREAD

**Issue by RagnarThorburn** [ac-pm/Inspeckage#7]
Using LG G4 on CyanogenMod 13, opening the config menu crashes the app.

**Comment by ac-pm** [comment]
You are using the version 1.1b ? http://repo.xposed.info/module/mobi.acpm.inspeckage

**Comment by RagnarThorburn** [comment]
Hello again, yes I'm on 1.1b

**Comment by sm4rk0** [comment]
Can't reproduce. Tried both after updating from 1.0b and fresh install. Wiped data for the app, but no crash on Config.
Moto X 1st generation, stock android 5.1, xposed version 80

**Comment by ac-pm** [comment]
https://github.com/ac-pm/Inspeckage/commit/aca1642b5cfe1c7ba1bef3ae29521efd6774fdac

"CyanogenMod 13" is Android 6.

-- onAttach (Activity activity)
This method was deprecated in API level 23.
Use onAttach(Context) instead.
http://developer.android.com/intl/pt-br/reference/android/app/Fragment.html#onAttach(android.app.Activity)

Tested in:
Genymotion Custom Phone 
Android 6 - API 23
Xposed 80
Inspeckage 1.1b

And

Genymotion Custom Phone 
Android 5.1.0 - API 22
Xposed 80
Inspeckage 1.1b
