### ISSUE TITLE
Launching the app which has been selected as the target results in the target app crashing as well as Inspeckage itself sometimes.

### ISSUE THREAD

**Issue by RagnarThorburn** [ac-pm/Inspeckage#8]
Running LG G4 on CyanogenMod13 with the xposed framework, if I've targeted an app and then launch it, it will crash the app every time and 9/10 Inspeckage crashes with it.

**Comment by ac-pm** [comment]
You are using the version 1.1b? http://repo.xposed.info/module/mobi.acpm.inspeckage 

these are the steps?

Open app
Click back button
Open navigation drawer and on Config item

**Comment by RagnarThorburn** [comment]
Hi, yeh I'm assuming 1.1b, steps:
Open app
Click hamburger menu to open navigation drawer
Click config and crash

**Comment by ac-pm** [comment]
"CyanogenMod 13" is Android 6.

-- onAttach (Activity activity)
This method was deprecated in API level 23.
Use onAttach(Context) instead.
http://developer.android.com/intl/pt-br/reference/android/app/Fragment.html#onAttach(android.app.Activity)

Tested in:
Genymotion Custom Phone 
Android 6 - API 23
Xposed 80
Inspeckage 1.1b

And

Genymotion Custom Phone 
Android 5.1.0 - API 22
Xposed 80
Inspeckage 1.1b

**Comment by ac-pm** [comment]
Can't reproduce.

Tested in:
Genymotion Custom Phone 
Android 6 - API 23
Xposed 80
Inspeckage 1.1b

And

Genymotion Custom Phone 
Android 5.1.0 - API 22
Xposed 80
Inspeckage 1.1b

**Comment by RagnarThorburn** [comment]
So you know full info:
LG G4
Android 6 - API 23
XPOSED 80
Inspeckage 1.1b

Problem with CyanogenMod maybe? I'm going back to stock at some point soon so I'll update if it's still an existing problem.

Nice job on the other issue though!

**Comment by youdy3000** [comment]
Hi @RagnarThorburn, was this a problem with only one specific app?

I ask because it may have code to crash the app when it detects hooking.

**Comment by ac-pm** [comment]
Please try v2.0

**Comment by eswariy** [comment]
Could anyone help me one:
1. how to read the files that download from the inspackage because i need to do analysis on that..
2. how to parse the contents into csv file
