### ISSUE TITLE
Module Disabled

### ISSUE THREAD

**Issue by youdy3000** [ac-pm/Inspeckage#9]
Hi @ac-pm,  Thank you so much for this tool.  It is exactly the tool I have been looking for.  I can get the web server running, launching an app from Inspeckage and I can view the web interface.

But I can't do the interesting stuff as I can't get passed the Module Disabled.  I have watched your video 10 times to see I was missing a step.  I got all files installed.  The only difference I know from your setup was:
 - I used xPosed SDK version for x86 (v23).  You used v22.
 - I am running an Android 6.0 on my GenyMotion Emulator.

![screenshot1](https://cloud.githubusercontent.com/assets/5367141/13708063/8fca5b36-e7a4-11e5-8ba5-7695e38c99a4.png)
![screenshot2](https://cloud.githubusercontent.com/assets/5367141/13708064/923a5204-e7a4-11e5-8973-44f87c39490a.png)
![screenshot3](https://cloud.githubusercontent.com/assets/5367141/13708068/942e272a-e7a4-11e5-8da1-f4d773466b46.png)

**Comment by ac-pm** [comment]
Thank you for the feedback!

In my "Genymotion Custom Phone" with android 6 (api 23) works great!

----
xposed-v80-sdk23-x86.zip instead of 22

![1-00](https://cloud.githubusercontent.com/assets/1753643/13717705/0e220a20-e7c2-11e5-939c-361c5d1d3495.png)

**Comment by ac-pm** [comment]
Hi @youdy3000, I closed the issue for now, if someone else has the problem I will reopen.
Please test the latest version.

**Comment by youdy3000** [comment]
Hi @ac-pm, I read the separate reply & did an clear app data & clear cache (on the target APK and Inspeckage) and this problem went away.

Great stuff.  You are the man!

**Comment by youdy3000** [comment]
Hi @ac-pm, for your information I think the problem was Hide My Root.  My target app has root detection.  I was hiding the root functionality to stop it being detected.  However, I think when I hid SU files Inspeckage always said Module Disabled.

My solution: 

1. Unhide SU files with Hide My Root
2. Restart the device and Inspeckage enabled in Xposed
3. Turn off other hooking Xposed frameworks (Android Eagle Eye)
4. Module is enabled.  Now I can Hide my Root.
5. Use Inspeckage to open the target app!

**Comment by baliganorbi** [comment]
Hi @ac-pm,

This module really seems to be exciting for me too, but I have the same problem that @youdy3000 mentioned. 

I cloned the git project of the Xposed module, imported into my Android studio, builded and installed it to my device successfully. After that I enabled the module in the XposedInstaller and rebooted the device, but launching the Inspeckage after reboot said that the module is not enabled and I cannot use its fully functionality. 

I use a physical device (Samsung Galaxy SII (GT-I9100) with Android version 4.4.4 (Cyanogenmod 11-20141115), XposedInstaller version 2.6.1. I attached some screenshots containing these information. 

In the logcat log I don't see any relevant error message during the usage of the application. (I attached a short excerpt right after starting the Inspeckage application UI)

Could you please advise? Thanks in advance!
![screenshot_2016-05-19-14-03-55](https://cloud.githubusercontent.com/assets/765761/15396985/b7bc8d4c-1dde-11e6-95ad-38282774350b.png)
![screenshot_2016-05-19-14-04-09](https://cloud.githubusercontent.com/assets/765761/15396984/b7bc2f6e-1dde-11e6-9f22-b603e05b28c4.png)
![screenshot_2016-05-19-14-04-14](https://cloud.githubusercontent.com/assets/765761/15396983/b7ba68f0-1dde-11e6-932a-df16ffae693e.png)
![screenshot_2016-05-19-14-04-21](https://cloud.githubusercontent.com/assets/765761/15396982/b7b9f032-1dde-11e6-99c6-d7046a2de164.png)

> I/Timeline( 4979): Timeline: Activity_launch_request id:mobi.acpm.inspeckage time:1573824
> I/ActivityManager( 4753): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=mobi.acpm.inspeckage/.ui.MainActivity bnds=[123,260][240,392]} from pid 4979
> W/BroadcastQueue( 4753): Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=4979, uid=10016) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
> W/BroadcastQueue( 4753): Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10016)
> I/Timeline( 6634): Timeline: Activity_idle id: android.os.BinderProxy@41db7830 time:1574020
> I/Timeline( 4753): Timeline: Activity_windows_visible id: ActivityRecord{423077c8 u0 mobi.acpm.inspeckage/.ui.MainActivity t6} time:1574300

**Comment by ac-pm** [comment]
Hi @baliganorbi, sorry but I cant help you, like the issue #24 please try android >= 5.1.x

At the moment android 4.x is out of scope and I never tried to use the Inspeckage in android 4.x.

If you do it work, please tell me.

**Comment by baliganorbi** [comment]
Thank you for your reply @ac-pm! I understand it. (it just would be great if it would be possible to use this tool on Android 4.x too) I am going to make a little investigation why it is not working, I will let you know if I get a better picture. 

Anyway, nice job and I hope the tool will have a great future! :)

**Comment by HumairaFasih** [comment]
Hi @ac-pm !

I ran into the same error on an emulated Google Nexus 5 with Android 7 on Genymotion v3.3.3
Couldn't make it switch to "Enabled" with any number of reboots/clearing cache for Inspeckage.

Please look into this

**Comment by HumairaFasih** [comment]
Edit: wasn't able to make it work with EdXposed, but it was enabled when I installed LSPosed framework. No reboots were needed either.
